# Generated by Django 5.0.4 on 2024-05-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0004_alter_like_unique_together_post_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
