# Generated by Django 5.0.4 on 2024-05-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0005_remove_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(related_name='posts', to='apka.hashtag'),
        ),
    ]
